### ISSUE TITLE
Price Feed

### ISSUE THREAD

**Issue by PatrickAlphaC** [codenamejason/hackmoney#36]
https://github.com/codenamejason/hackmoney/blob/6330429bf90b2e9235a82acc1e3d1f1ac711ed51/front-end/contracts/bandprotocol/Oracle.sol#L3

hi codenamejson,
I was looking through hackmoney projects to see if I could lend a hand anywhere, and I saw that you might be able to get ETH-USD price from the Chainlink reference contract instead. It gets its data from multiple nodes (decentralization woo!), and is free at the moment :D

https://feeds.chain.link/eth-usd
https://docs.chain.link/docs/using-chainlink-reference-contracts

In any case, let me know if I can lend a hand here.

**Comment by codenamejason** [comment]
That would be great just clone a new branch. I wanted to use Chainlink for sure. My name is Jason  and would appreciate any help.

**Comment by codenamejason** [comment]
Decentralized is key and we will need to move tokens around fairly often. Definitely need feed for when we add the arbitrage opportunities using Aave flashloans.

**Comment by codenamejason** [comment]
I guess I lost you...

**Comment by PatrickAlphaC** [comment]
Check your pull requests :)

**Comment by codenamejason** [comment]
Ha Ha, you rock!!

**Comment by codenamejason** [comment]
How to update the price without redeploying contract? The price stays the same.

**Comment by PatrickAlphaC** [comment]
Just make another call to the reference contract, it updates about every 30 - 60 minutes, or when there is a price difference of greater than 0.5%. You don’t have to redeploy. Just call that request price function

**Comment by PatrickAlphaC** [comment]
Every price pair (ETH/USD, DAI/ETH) you’ll have to deploy a referenceConsumer (a new contract with that pairs address in the constructor). Once it’s deployed, you can always just call the “getLatestPrice” function

**Comment by codenamejason** [comment]
Understood. Thanks. Another question.

![image](https://user-images.githubusercontent.com/9419140/82700651-a21cf900-9c3c-11ea-8f1a-f88299c8d962.png)

what are these used for

**Comment by PatrickAlphaC** [comment]
You can get the entire history of every price that the reference contract has ever posted. You just enter the number of posts back, and timestamp as well. 

So this is for historical prices.

**Comment by codenamejason** [comment]
Too cool, thanks again man.
